### ISSUE TITLE
Include screenshots?

### ISSUE THREAD

**Issue by 2lag** [leduyquang753/csgo-hud#1]
Just a suggestion, but people browsing Github will mostly only be interested if they can see the result of what you're working on!

**Comment by leduyquang753** [comment]
As you can see the project has just gotten its very first commit, nothing has even appeared in front of my own eyes yet. Stay tuned.

**Comment by 2lag** [comment]
Gotcha. I did in fact notice that, I just thought some advice could be of use to you, as many of your repositories are lacking that aspect. However, your words back are of use to any future viewers of this, so thank you for letting us know. I wish you the best of luck, and be certain that there will be eyes on the project!
